# this file defines the CI pipeline for the project. It runs on every     push to the main branch and performs the following steps:
    # 1. Checks out the code from the repository
    # 2. Sets up Node.js environment
    # 3. Installs the project dependencies
    # 4. Lints the code to ensure code quality
    # 5. Builds the project
    # 6. Builds a Docker image for the application


name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22  

      - name: Install deps
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Docker Build
        run: docker build -t vite-app .